IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
        debian.vm.network "forwarded_port", guest: 22, host: 2230, host_ip: "127.0.0.1"
        zabbix.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
        debian.vm.hostname = "debian"
    end

    config.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    # Načtení a provedení scriptu install-zabbix-agent2.sh
    config.vm.provision "shell", path: "install-zabbix.sh"

    # Načtení a provedení scriptu configure-zabbix-agent2.sh
    config.vm.provision "shell", path: "configure-zabbix-agent2conf.sh"
end